### ISSUE TITLE
Execution failure

### ISSUE THREAD

**Issue by cjwoodruff50** [marcus1487/nanoraw#35] opened 2017-03-22 03:47 UTC
Any suggestions for making progress on this?
Have not succeeded in getting successful run.  Initial error was
KeyError: "Couldn't delete link (Link count would be negative)"
Edited resquigglepy to put Try clause around the write block.  The subsequent run gave many errors - see list below where the part "Exception ..." occurred copiously
Exception RuntimeError: RuntimeError("Can't decrement id ref count (Can't decrement ref. count)",) in 'h5py._objects.ObjectID.__dealloc__' ignored
Exception RuntimeError: RuntimeError("Can't decrement id ref count (Can't decrement ref. count)",) in 'h5py._objects.ObjectID.__dealloc__' ignored

Failed reads summary:
        Unable to open file (Truncated file: eof = 998702, sblock->base_addr = 0, stored_eoa = 1004464) :       1
        Unable to open file (Truncated file: eof = 1717568, sblock->base_addr = 0, stored_eoa = 1725494) :      1
        Unable to create attribute (Duplicate entry in cache.) :        12
        FAST5 file is not writable. :   3207
        list index out of range :       1
        Reached maximum number of changepoints for a single indel :     3452
        Unable to create group (Addr overflow, addr = 2349844, size=328, eoa=2349140) : 1
        Unable to open file (Truncated file: eof = 2013509, sblock->base_addr = 0, stored_eoa = 2020990) :      1
        Unable to create group (Addr overflow, addr = 2719661, size=328, eoa=2718957) : 1
        Read sequence from SAM and cooresponding cigar string do not agree. :   179
        Unable to create group (Addr overflow, addr = 1561488, size=328, eoa=1560784) : 1
        Unable to create group (Addr overflow, addr = 2463687, size=328, eoa=2462983) : 1
        Error writing file. Likely a h5py error. :      11
        Unable to create group (Addr overflow, addr = 1805340, size=328, eoa=1804636) : 1
        Alignment not produced. :       671
        Unable to open file (File is already open for read-only) :      335
        Error opening file. Likely a corrupted file. :  11
        Unable to open file (Truncated file: eof = 2341342, sblock->base_addr = 0, stored_eoa = 2346424) :      1
        Can't decrement id ref count (Can't decrement ref. count) :     154911

**Comment by marcus1487** [comment] 2017-03-22 04:04
It looks like some if your files are not writeable. Have you checked the write permissions for the fast5 files? Some of the other errors may be coming from files being simultaneously accessed. Make sure there are not old spawned processes from a previous nanoraw genome_resquiggle run (via top of htop). I would also check to see that you have disk space on the drive on which these files are located.

I hope some of these suggestions might help. If not are the errors reproducible? If the failure modes are consistent would you mind sending me the failed reads summary file and a small sample of the failed fast5 files.

**Comment by cjwoodruff50** [comment] 2017-03-22 05:01
Marcus,
                Thanks for your quick reply.  I’ll follow up on each of these suggestions over the next 24hours.  I have no problem with disk space as I’m on an institutional server with plenty of memory.  The files SHOULD all be write accessible but I’ll double check this.  I am very keen to get your code running as I like the potential of the method you have developed to address a range of base modifications.

Chris

**Comment by marcus1487** [comment] 2017-03-22 23:25
Another thought is that your h5py may be out of date. See this issue: https://github.com/h5py/h5py/issues/495

Try updating h5py and re-running.

**Comment by cjwoodruff50** [comment] 2017-03-23 04:30
Marcus,
                This looks like a good suggestion.  I’m following it up with our IT people (I don’t have administrator privileges) and am cautiously optimistic based on the similarity of the error messages to those reported on the link to which you referred.
Chris

**Comment by marcus1487** [comment] 2017-03-28 23:08
Hi Chris,

Have you resolved this issue? Was it an issue with your h5py version? If so I will add a dependency on the h5py package version to avoid this issue in the future.

P.S. You might try python virtual environments (http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/) for machines on which you don't have root. I generally use python envs even when I do have sudo given the general headaches with python packaging. Just a thought;)

**Comment by cjwoodruff50** [comment] 2017-03-28 23:36
Marcus,
                I have not resolved the problem yet but I am still following up a couple of avenues.  Be assured I will let you know as soon as I find a solution.  Not being either a Unix or Python guru I can be rather dependent on others at times in chasing things down.  Thanks for your last suggestion- I’ll follow this up, too.
Chris

**Comment by marcus1487** [comment] 2017-06-23 21:39
Hi Chris,

I have just recently added a number of additional error checks around accessing and closing fast5 files. I think these will both give better indications of where these errors are happening as well as allowing execution for those files that are formatted correctly. If you update to the most recent version on github (not pypi, yet, but soon) this should resolve most all of your errors (or at least report them correctly in the nanoraw failed reads format). I will mark this issue as resolved, but if any of these errors persist please post and I will reopen the repository. Thanks!

**Closed as completed by marcus1487** 2017-06-23 21:39 UTC

**Comment by cjwoodruff50** [comment] 2017-06-23 21:54
Marcus,
                Thanks for this.  I’ll be getting back to nanoraw in the coming week, hopefully with the support of a much better computer man, Scott Gigante, than me to help.  We’ve been distracted by other activities – such as RNAseq processing – recently.  But base modifications are our primary focus still.

Chris
